// <auto-generated />
using System;
using Faahi.Controllers.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faahi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113120805_attr")]
    partial class attr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Faahi.Model.Admin.sa_country_regions", b =>
                {
                    b.Property<Guid>("country_region_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("avl_countries_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("region_name")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("country_region_id");

                    b.ToTable("sa_country_regions");
                });

            modelBuilder.Entity("Faahi.Model.Admin.sa_regions", b =>
                {
                    b.Property<Guid>("region_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("country_region_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("parent_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("region_name")
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("sa_country_regionscountry_region_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("region_id");

                    b.HasIndex("sa_country_regionscountry_region_id");

                    b.ToTable("sa_regions");
                });

            modelBuilder.Entity("Faahi.Model.Admin.super_admin", b =>
                {
                    b.Property<Guid>("super_admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<string>("user_type")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("super_admin_id");

                    b.HasIndex(new[] { "email" }, "email");

                    b.HasIndex(new[] { "phone" }, "phone");

                    b.HasIndex(new[] { "status" }, "status");

                    b.HasIndex(new[] { "super_admin_id" }, "super_admin_id")
                        .IsUnique();

                    b.ToTable("super_admin");
                });

            modelBuilder.Entity("Faahi.Model.Email_verify.am_emailVerifications", b =>
                {
                    b.Property<Guid>("Email_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("isExpired")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("token")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("tokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<string>("userType")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("verificationType")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("verified")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("Email_id");

                    b.ToTable("am_emailVerifications");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_Parties", b =>
                {
                    b.Property<Guid>("party_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("default_currency")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("display_name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("legal_name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("party_type")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("payable_name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("tax_id")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("vsco_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("party_id");

                    b.ToTable("st_Parties");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_PartyAddresses", b =>
                {
                    b.Property<Guid>("address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address_type")
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("ap_Vendorsvendor_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ar_Customerscustomer_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("country")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("customer_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("is_default")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("line1")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("line2")
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("party_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("postal_code")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("region")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("st_PartyRolesparty_role_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("vendor_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("address_id");

                    b.HasIndex("ap_Vendorsvendor_id");

                    b.HasIndex("ar_Customerscustomer_id");

                    b.HasIndex("st_PartyRolesparty_role_id");

                    b.ToTable("st_PartyAddresses");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_PartyContacts", b =>
                {
                    b.Property<Guid>("contact_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("is_primary")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("last_name")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("party_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("st_PartyAddressesaddress_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("title")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("contact_id");

                    b.HasIndex("st_PartyAddressesaddress_id");

                    b.ToTable("st_PartyContacts");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_PartyRoles", b =>
                {
                    b.Property<Guid>("party_role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("party_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("role")
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("st_Partiesparty_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("party_role_id");

                    b.HasIndex("st_Partiesparty_id");

                    b.ToTable("st_PartyRoles");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_StoreCategories", b =>
                {
                    b.Property<Guid>("store_category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("category_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("is_selected")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<Guid?>("store_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("store_category_id");

                    b.HasIndex("category_id");

                    b.HasIndex("is_selected");

                    b.HasIndex("store_id");

                    b.ToTable("st_StoreCategories");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_StoreCategoryTemplates", b =>
                {
                    b.Property<Guid>("store_category_template_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("category_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("store_type")
                        .HasColumnType("varchar(50)");

                    b.HasKey("store_category_template_id");

                    b.HasIndex("category_id");

                    b.HasIndex("store_type");

                    b.ToTable("st_StoreCategoryTemplates");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_StoresAddres", b =>
                {
                    b.Property<Guid>("store_address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address_type")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("is_current")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("line1")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("line2")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("postal_code")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("st_storesstore_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("store_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("valid_from")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("valid_to")
                        .HasColumnType("datetime");

                    b.HasKey("store_address_id");

                    b.HasIndex("address_type");

                    b.HasIndex("is_current");

                    b.HasIndex("st_storesstore_id");

                    b.HasIndex("store_id");

                    b.HasIndex("valid_from");

                    b.ToTable("st_StoresAddres");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_UserRoles", b =>
                {
                    b.Property<Guid>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("role_name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("role_id");

                    b.HasIndex("company_id");

                    b.HasIndex("description");

                    b.HasIndex("role_name");

                    b.ToTable("st_UserRoles");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_UserStoreAccess", b =>
                {
                    b.Property<Guid>("store_access_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("role_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<Guid?>("store_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("store_access_id");

                    b.HasIndex("created_at");

                    b.HasIndex("role_id");

                    b.HasIndex("status");

                    b.HasIndex("store_id");

                    b.HasIndex("user_id");

                    b.ToTable("st_UserStoreAccess");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_store_currencies", b =>
                {
                    b.Property<Guid>("store_currency_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("currency_code")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("is_default")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<Guid?>("st_StoresAddresstore_address_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("store_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("store_currency_id");

                    b.HasIndex("currency_code");

                    b.HasIndex("st_StoresAddresstore_address_id");

                    b.HasIndex("store_currency_id");

                    b.HasIndex("store_id");

                    b.ToTable("st_store_currencies");
                });

            modelBuilder.Entity("Faahi.Model.am_users", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address1")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("address2")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("edit_date_time")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("emailVerified")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("googleId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("isGoogleSignUp")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("lastName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("userName")
                        .HasColumnType("varchar(32)");

                    b.HasKey("userId");

                    b.ToTable("am_users");
                });

            modelBuilder.Entity("Faahi.Model.am_vcos.ap_Vendors", b =>
                {
                    b.Property<Guid>("vendor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ap_control_account")
                        .HasColumnType("varchar(40)");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("contact_email")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("contact_name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("contact_phone1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("contact_phone2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("contact_website")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("note")
                        .HasColumnType("varchar(40)");

                    b.Property<Guid?>("payment_term_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("preferred_payment_method")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("tex_identification_number")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<string>("vendor_code")
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("withholding_tax_rate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("vendor_id");

                    b.ToTable("ap_Vendors");
                });

            modelBuilder.Entity("Faahi.Model.am_vcos.ar_Customers", b =>
                {
                    b.Property<Guid>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("contact_email")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("contact_name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("contact_phone1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("contact_phone2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("credit_hold")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<decimal?>("credit_limit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("customer_code")
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("default_billing_address_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("default_shipping_address_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("loyalty_level")
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("loyalty_points")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("note")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("payment_term_id")
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("price_tier_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("tax_exempt")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("tex_identification_number")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("customer_id");

                    b.ToTable("ar_Customers");
                });

            modelBuilder.Entity("Faahi.Model.co_business.co_address", b =>
                {
                    b.Property<Guid>("company_address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("city")
                        .HasColumnType("varchar(60)");

                    b.Property<Guid?>("co_businesscompany_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("contact_person")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("country")
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("edit_date_time")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("postal_code")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("state")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("street_1")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("street_2")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("telephone_1")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("telephone_2")
                        .HasColumnType("varchar(20)");

                    b.HasKey("company_address_id");

                    b.HasIndex("co_businesscompany_id");

                    b.ToTable("co_address");
                });

            modelBuilder.Entity("Faahi.Model.co_business.co_avl_countries", b =>
                {
                    b.Property<Guid>("avl_countries_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("country_code")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("currency_code")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("currency_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("dialling_code")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("flag")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("serv_available")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("avl_countries_id");

                    b.ToTable("co_avl_countries");
                });

            modelBuilder.Entity("Faahi.Model.co_business.co_business", b =>
                {
                    b.Property<Guid>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("business_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("company_code")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("country")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("createdSites")
                        .HasColumnType("int");

                    b.Property<int?>("createdSites_users")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("edit_date_time")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("logo_fileName")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("plan_type")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("reg_no")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("sites_allowed")
                        .HasColumnType("int");

                    b.Property<int?>("sites_users_allowed")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("tin_number")
                        .HasColumnType("varchar(50)");

                    b.HasKey("company_id");

                    b.HasIndex("business_name");

                    b.HasIndex("country");

                    b.HasIndex("createdSites");

                    b.HasIndex("createdSites_users");

                    b.HasIndex("created_at");

                    b.HasIndex("edit_date_time");

                    b.HasIndex("edit_user_id");

                    b.HasIndex("email");

                    b.HasIndex("phoneNumber");

                    b.HasIndex("plan_type");

                    b.HasIndex("reg_no");

                    b.HasIndex("sites_allowed");

                    b.HasIndex("sites_users_allowed");

                    b.HasIndex("tin_number");

                    b.ToTable("co_business");
                });

            modelBuilder.Entity("Faahi.Model.countries.avl_countries", b =>
                {
                    b.Property<Guid>("avl_countries_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("country_code")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("currency_code")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("currency_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("dialling_code")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("flag")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("serv_available")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("avl_countries_id");

                    b.ToTable("avl_countries");
                });

            modelBuilder.Entity("Faahi.Model.countries.fx_Currencies", b =>
                {
                    b.Property<Guid>("currency_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("country_code")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("country_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("currency_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("currency_symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("currency_id");

                    b.HasIndex("currency_id");

                    b.HasIndex("currency_name");

                    b.ToTable("fx_Currencies");
                });

            modelBuilder.Entity("Faahi.Model.countries.fx_timezones", b =>
                {
                    b.Property<Guid>("timezone_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("currency_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("fx_Currenciescurrency_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("timezone_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("timezone_id");

                    b.HasIndex("fx_Currenciescurrency_id");

                    b.ToTable("fx_Timezones");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_AttributeValues", b =>
                {
                    b.Property<Guid>("value_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("attribute_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("color_name")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("display_order")
                        .HasColumnType("int");

                    b.Property<Guid?>("im_ProductAttributesattribute_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("value_id");

                    b.HasIndex("im_ProductAttributesattribute_id");

                    b.ToTable("im_AttributeValues");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_InventoryLedger", b =>
                {
                    b.Property<Guid>("ledger_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cost_method")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("reference_note")
                        .HasColumnType("varchar(400)");

                    b.Property<Guid?>("source_doc_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("source_doc_line")
                        .HasColumnType("int");

                    b.Property<string>("source_doc_type")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("transaction_date")
                        .HasColumnType("datetime");

                    b.Property<string>("transaction_type")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("unit_cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("uom_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ledger_id");

                    b.HasIndex("source_doc_id");

                    b.HasIndex("source_doc_type");

                    b.HasIndex("transaction_date");

                    b.HasIndex("user_id");

                    b.HasIndex("variant_id");

                    b.ToTable("im_InventoryLedger");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_Lots", b =>
                {
                    b.Property<Guid>("lot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("committed_qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("consign_qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<DateOnly?>("expiry_date")
                        .HasColumnType("date");

                    b.Property<string>("is_on_hold")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("lot_code")
                        .HasColumnType("varchar(80)");

                    b.Property<DateOnly?>("mfg_date")
                        .HasColumnType("date");

                    b.Property<string>("note")
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("promo_price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("lot_id");

                    b.HasIndex("expiry_date");

                    b.HasIndex("is_on_hold");

                    b.HasIndex("lot_code");

                    b.HasIndex("variant_id");

                    b.ToTable("im_Lots");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_PriceTiers", b =>
                {
                    b.Property<Guid>("price_tier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("im_product_subvariantsub_variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("sub_variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("price_tier_id");

                    b.HasIndex("im_product_subvariantsub_variant_id");

                    b.ToTable("im_PriceTiers");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductAttributes", b =>
                {
                    b.Property<Guid>("attribute_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("display_order")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("attribute_id");

                    b.HasIndex("company_id");

                    b.HasIndex("name");

                    b.ToTable("im_ProductAttributes");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductCategories", b =>
                {
                    b.Property<Guid>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("category_name")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("edit_date_time")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("image_url")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("is_active")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<Guid?>("parent_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("category_id");

                    b.HasIndex("Level");

                    b.HasIndex("category_name");

                    b.HasIndex("is_active");

                    b.HasIndex("parent_id");

                    b.ToTable("im_ProductCategories");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductImages", b =>
                {
                    b.Property<Guid>("image_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("display_order")
                        .HasColumnType("int");

                    b.Property<Guid?>("im_ProductVariantsvariant_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("image_url")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("is_primary")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<Guid?>("product_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("uploaded_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("image_id");

                    b.HasIndex("im_ProductVariantsvariant_id");

                    b.ToTable("im_ProductImages");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductVariantPrices", b =>
                {
                    b.Property<Guid>("variant_price_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("currency")
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("im_PriceTiersprice_tier_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("price_tier_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("sub_variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("variant_price_id");

                    b.HasIndex("im_PriceTiersprice_tier_id");

                    b.ToTable("im_ProductVariantPrices");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductVariants", b =>
                {
                    b.Property<Guid>("variant_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("barcovendor_part_number")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("base_price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("im_Productsproduct_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("is_default")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<Guid?>("product_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sku")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("uom_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("variant_id");

                    b.HasIndex("im_Productsproduct_id");

                    b.ToTable("im_ProductVariants");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_Products", b =>
                {
                    b.Property<Guid>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("allow_below_zero")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("brand")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("category_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("dutyP")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("featured_item")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("fixed_price")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("has_free_item")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("ignore_direct")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("is_multi_unit")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("kitchen_type")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("low_stock_alert")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("published")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("restrict_HS")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("restrict_deciaml_qty")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("stock_flag")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<Guid?>("sub_category_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("sub_sub_category_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tax_class_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("thumbnail_url")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("title")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("track_expiry")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("vendor_Code")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("product_id");

                    b.HasIndex("company_id");

                    b.HasIndex("title");

                    b.ToTable("im_Products");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_SellerInventory", b =>
                {
                    b.Property<Guid>("seller_inventory_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Consignment_quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Rack_no")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("allow_Inter_Location_Transfer")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("bin_number")
                        .HasColumnType("varchar(25)");

                    b.Property<decimal?>("committed_quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("on_hold")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<decimal?>("reorder_level")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("sales_count")
                        .HasColumnType("int");

                    b.Property<string>("sales_on_hold")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<decimal>("stock_quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("store_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("uom_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("seller_inventory_id");

                    b.HasIndex("store_id");

                    b.HasIndex("user_id");

                    b.HasIndex("variant_id");

                    b.ToTable("im_SellerInventory");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_StoreVariantInventory", b =>
                {
                    b.Property<Guid>("store_variant_inventory_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("bin_number")
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal?>("committed_quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("im_ProductVariantsvariant_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("on_hand_quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("store_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("store_variant_inventory_id");

                    b.HasIndex("im_ProductVariantsvariant_id");

                    b.HasIndex("store_id");

                    b.HasIndex("variant_id");

                    b.ToTable("im_StoreVariantInventory");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_UnitsOfMeasure", b =>
                {
                    b.Property<Guid>("uom_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("abbreviation")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("uom_id");

                    b.ToTable("im_UnitsOfMeasures");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_VariantAttributes", b =>
                {
                    b.Property<Guid>("varient_attribute_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("attribute_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("im_ProductVariantsvariant_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("value_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("varient_attribute_id");

                    b.HasIndex("im_ProductVariantsvariant_id");

                    b.ToTable("im_VariantAttributes");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_item_Category", b =>
                {
                    b.Property<Guid>("item_class_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sales_count")
                        .HasColumnType("int");

                    b.Property<string>("categoryImage")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("categoryType")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("code")
                        .HasColumnType("varchar(10)");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("edit_date_time")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("item_class")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("item_count")
                        .HasColumnType("int");

                    b.Property<string>("publish")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("item_class_id");

                    b.ToTable("im_item_Category");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_item_site", b =>
                {
                    b.Property<Guid>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("bin_number")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("c_price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("committed_quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("im_sitesite_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("on_hand_quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("on_hold")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("primary_vendor_id")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("purchase_order_quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("sales_order_quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("site_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("item_id");

                    b.HasIndex("im_sitesite_id");

                    b.ToTable("im_item_site");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_item_subcategory", b =>
                {
                    b.Property<Guid>("item_subclass_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("edit_date_time")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("im_item_Categoryitem_class_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("item_class_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("item_subclass_id");

                    b.HasIndex("im_item_Categoryitem_class_id");

                    b.ToTable("im_item_subcategory");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_product_subvariant", b =>
                {
                    b.Property<Guid>("sub_variant_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("avg_cost")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("deduct_qnty")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("fixed_price")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("generateBarcode")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("item_barcode")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("last_cost")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("list_price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("minimum_selling")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("modal_number")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("product_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("profit_p")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("shipping_height")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("shipping_length")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("shipping_weight")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("shipping_width")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("standard_cost")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("total_volume")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("total_weight")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("unit_breakdown")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("variantType")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("variantValue")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ws_price")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("sub_variant_id");

                    b.ToTable("im_product_subvariant");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_products_tag", b =>
                {
                    b.Property<Guid>("tag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("edit_date_time")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("item_class_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("item_subclass_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("tag_id");

                    b.ToTable("im_products_tag");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_purchase_listing", b =>
                {
                    b.Property<Guid>("listing_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("currency_code")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("discount_amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("doc_total")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("edit_user_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("exchange_rate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("freight_amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("notes")
                        .HasColumnType("varchar(400)");

                    b.Property<decimal?>("other_expenses")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("payment_mode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("purchase_type")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("received_at")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("site_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("sub_total")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("supplier_invoice_date")
                        .HasColumnType("datetime");

                    b.Property<string>("supplier_invoice_no")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("tax_amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("vendor_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("listing_id");

                    b.ToTable("im_purchase_listing");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_purchase_listing_details", b =>
                {
                    b.Property<Guid>("detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("discount_amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("expiry_date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("freight_amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("im_purchase_listinglisting_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("line_total")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("listing_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("notes")
                        .HasColumnType("varchar(400)");

                    b.Property<decimal?>("other_expenses")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("product_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("sub_variant_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("tax_amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("unit_price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("uom_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("detail_id");

                    b.HasIndex("im_purchase_listinglisting_id");

                    b.ToTable("im_purchase_listing_details");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_site", b =>
                {
                    b.Property<Guid>("site_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("avl_countries_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_address_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("site_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("tin_number")
                        .HasColumnType("varchar(100)");

                    b.HasKey("site_id");

                    b.ToTable("im_site");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_site_users", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("edit_date_time")
                        .HasColumnType("datetime");

                    b.Property<string>("edit_user_id")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("lastName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("site_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("site_user_code")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("userName")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("userRole")
                        .HasColumnType("varchar(20)");

                    b.HasKey("userId");

                    b.ToTable("im_site_users");
                });

            modelBuilder.Entity("Faahi.Model.st_sellers.st_Users", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Full_name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("account_type")
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("registration_date")
                        .HasColumnType("datetime");

                    b.Property<string>("status")
                        .HasColumnType("varchar(20)");

                    b.HasKey("user_id");

                    b.HasIndex("Full_name");

                    b.HasIndex("account_type");

                    b.HasIndex("company_id");

                    b.HasIndex("email");

                    b.HasIndex("phone");

                    b.HasIndex("registration_date");

                    b.HasIndex("status");

                    b.ToTable("st_Users");
                });

            modelBuilder.Entity("Faahi.Model.st_sellers.st_stores", b =>
                {
                    b.Property<Guid>("store_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<TimeOnly?>("default_close_time")
                        .HasColumnType("time");

                    b.Property<string>("default_currency")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("default_invoice_init")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("default_invoice_template")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("default_quote_init")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("default_receipt_template")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("last_transaction_date")
                        .HasColumnType("date");

                    b.Property<string>("low_stock_alert_email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("message_on_invoice")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("message_on_receipt")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("phone1")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("phone2")
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal?>("plastic_bag_tax_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("service_charge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("store_location")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("store_name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("store_type")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tax_activity_no")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tax_identification_number")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tax_inclusive_price")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("tax_payer_name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("timezone_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("store_id");

                    b.HasIndex("company_id");

                    b.HasIndex("created_at");

                    b.HasIndex("status");

                    b.HasIndex("store_name");

                    b.HasIndex("store_type");

                    b.ToTable("st_stores");
                });

            modelBuilder.Entity("Faahi.Model.table_key.am_table_next_key", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("next_key")
                        .HasColumnType("int");

                    b.Property<string>("site_code")
                        .HasColumnType("varchar(16)");

                    b.HasKey("name");

                    b.ToTable("am_table_next_key");
                });

            modelBuilder.Entity("Faahi.Model.Admin.sa_regions", b =>
                {
                    b.HasOne("Faahi.Model.Admin.sa_country_regions", null)
                        .WithMany("sa_regions")
                        .HasForeignKey("sa_country_regionscountry_region_id");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_PartyAddresses", b =>
                {
                    b.HasOne("Faahi.Model.am_vcos.ap_Vendors", null)
                        .WithMany("st_PartyAddresses")
                        .HasForeignKey("ap_Vendorsvendor_id");

                    b.HasOne("Faahi.Model.am_vcos.ar_Customers", null)
                        .WithMany("st_PartyAddresses")
                        .HasForeignKey("ar_Customerscustomer_id");

                    b.HasOne("Faahi.Model.Shared_tables.st_PartyRoles", null)
                        .WithMany("st_PartyAddresses")
                        .HasForeignKey("st_PartyRolesparty_role_id");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_PartyContacts", b =>
                {
                    b.HasOne("Faahi.Model.Shared_tables.st_PartyAddresses", null)
                        .WithMany("PartyContacts")
                        .HasForeignKey("st_PartyAddressesaddress_id");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_PartyRoles", b =>
                {
                    b.HasOne("Faahi.Model.Shared_tables.st_Parties", null)
                        .WithMany("st_PartyRoles")
                        .HasForeignKey("st_Partiesparty_id");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_StoreCategories", b =>
                {
                    b.HasOne("Faahi.Model.st_sellers.st_stores", "Stores")
                        .WithMany()
                        .HasForeignKey("store_id");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_StoresAddres", b =>
                {
                    b.HasOne("Faahi.Model.st_sellers.st_stores", null)
                        .WithMany("st_StoresAddres")
                        .HasForeignKey("st_storesstore_id");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_store_currencies", b =>
                {
                    b.HasOne("Faahi.Model.Stores.st_StoresAddres", null)
                        .WithMany("st_store_currencies")
                        .HasForeignKey("st_StoresAddresstore_address_id");
                });

            modelBuilder.Entity("Faahi.Model.co_business.co_address", b =>
                {
                    b.HasOne("Faahi.Model.co_business.co_business", null)
                        .WithMany("co_addresses")
                        .HasForeignKey("co_businesscompany_id");
                });

            modelBuilder.Entity("Faahi.Model.countries.fx_timezones", b =>
                {
                    b.HasOne("Faahi.Model.countries.fx_Currencies", null)
                        .WithMany("fx_timezones")
                        .HasForeignKey("fx_Currenciescurrency_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_AttributeValues", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_ProductAttributes", null)
                        .WithMany("im_AttributeValues")
                        .HasForeignKey("im_ProductAttributesattribute_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_PriceTiers", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_product_subvariant", null)
                        .WithMany("im_PriceTiers")
                        .HasForeignKey("im_product_subvariantsub_variant_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductImages", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_ProductVariants", null)
                        .WithMany("im_ProductImages")
                        .HasForeignKey("im_ProductVariantsvariant_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductVariantPrices", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_PriceTiers", null)
                        .WithMany("im_ProductVariantPrices")
                        .HasForeignKey("im_PriceTiersprice_tier_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductVariants", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_Products", null)
                        .WithMany("im_ProductVariants")
                        .HasForeignKey("im_Productsproduct_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_StoreVariantInventory", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_ProductVariants", null)
                        .WithMany("im_StoreVariantInventory")
                        .HasForeignKey("im_ProductVariantsvariant_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_VariantAttributes", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_ProductVariants", null)
                        .WithMany("im_VariantAttributes")
                        .HasForeignKey("im_ProductVariantsvariant_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_item_site", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_site", null)
                        .WithMany("im_item_site")
                        .HasForeignKey("im_sitesite_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_item_subcategory", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_item_Category", null)
                        .WithMany("im_item_subcategory")
                        .HasForeignKey("im_item_Categoryitem_class_id");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_purchase_listing_details", b =>
                {
                    b.HasOne("Faahi.Model.im_products.im_purchase_listing", null)
                        .WithMany("im_purchase_listing_details")
                        .HasForeignKey("im_purchase_listinglisting_id");
                });

            modelBuilder.Entity("Faahi.Model.Admin.sa_country_regions", b =>
                {
                    b.Navigation("sa_regions");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_Parties", b =>
                {
                    b.Navigation("st_PartyRoles");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_PartyAddresses", b =>
                {
                    b.Navigation("PartyContacts");
                });

            modelBuilder.Entity("Faahi.Model.Shared_tables.st_PartyRoles", b =>
                {
                    b.Navigation("st_PartyAddresses");
                });

            modelBuilder.Entity("Faahi.Model.Stores.st_StoresAddres", b =>
                {
                    b.Navigation("st_store_currencies");
                });

            modelBuilder.Entity("Faahi.Model.am_vcos.ap_Vendors", b =>
                {
                    b.Navigation("st_PartyAddresses");
                });

            modelBuilder.Entity("Faahi.Model.am_vcos.ar_Customers", b =>
                {
                    b.Navigation("st_PartyAddresses");
                });

            modelBuilder.Entity("Faahi.Model.co_business.co_business", b =>
                {
                    b.Navigation("co_addresses");
                });

            modelBuilder.Entity("Faahi.Model.countries.fx_Currencies", b =>
                {
                    b.Navigation("fx_timezones");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_PriceTiers", b =>
                {
                    b.Navigation("im_ProductVariantPrices");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductAttributes", b =>
                {
                    b.Navigation("im_AttributeValues");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_ProductVariants", b =>
                {
                    b.Navigation("im_ProductImages");

                    b.Navigation("im_StoreVariantInventory");

                    b.Navigation("im_VariantAttributes");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_Products", b =>
                {
                    b.Navigation("im_ProductVariants");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_item_Category", b =>
                {
                    b.Navigation("im_item_subcategory");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_product_subvariant", b =>
                {
                    b.Navigation("im_PriceTiers");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_purchase_listing", b =>
                {
                    b.Navigation("im_purchase_listing_details");
                });

            modelBuilder.Entity("Faahi.Model.im_products.im_site", b =>
                {
                    b.Navigation("im_item_site");
                });

            modelBuilder.Entity("Faahi.Model.st_sellers.st_stores", b =>
                {
                    b.Navigation("st_StoresAddres");
                });
#pragma warning restore 612, 618
        }
    }
}
